baseURL = ""
relativeurls = true
languageCode = "en-us"
title = "entan.gl"
theme = "binario"
enableEmoji = true

[params]
    customCSS = [
        "css/mine.css"
    ]

[menus]

    [[menus.main]]
    name = "GitHub"
    url = "https://github.com/empathicqubit"

    [[menus.main]]
    name = "Twitter"
    url = "https://twitter.com/empathicqubit"

[Params]
  post_meta = ["date", "categories"] # Enable post meta fields in given order

[Params.Share]
  facebook = true
  twitter = true
  reddit = true
  telegram = true
  linkedin = true
  vk = true
  pocket = true
